import { DvelopContext, DvelopOptions, dvelopFetch } from "@dvelop-sdk/core";
import { ensureSuccessResponse } from "../../utils/identityprovider-error";

/**
 * Used for authentication in the d.velop cloud. Refer to the [documentation](https://developer.d-velop.de/documentation/idpapi/en/identityprovider-app-201523580.html#validating-the-login) for further information.
 * @category Authentication
 */
export interface AuthSession {
  /** This key will validate your requests (usually sent as Bearer-Token). **The AuthSessionId should be kept secret and never be publicly available** */
  id: string;
  /** Date at which the AuthSessionId will no longer be valid. */
  expire: Date;
}

/**
 * Default `onResponse` provided to the {@link getAuthSession}-function. See [Advanced Topics](https://github.com/d-velop/dvelop-sdk-node#advanced-topics) for more information.
 * @internal
 * @category Authentication
 */
export async function onResponse(response: Response): Promise<AuthSession> {
  await ensureSuccessResponse(response);
  const data: any = await response.json();
  return {
    id: data.AuthSessionId,
    expire: new Date(data.Expire)
  };
}

/**
 * Returns an {@link AuthSession} based on an API-Key. API-Keys can be generated by d.velop cloud tenant administrators.
 * **The AuthSessionId should be kept secret and never be publicly available.**
 *
 *
 * ```typescript
 * import { getAuthSession } from "@dvelop-sdk/identityprovider";
 *
 * const authSession = await getAuthSession({
 *   systemBaseUri: "https://monster-ag.d-velop.cloud",
 *   authSessionId: "dQw4w9WgXcQ"
 * });
 *
 * console.log(authSession);
 * ```
 *
 * @category Authentication
 */
export async function getAuthSession(context: DvelopContext): Promise<AuthSession>;
export async function getAuthSession<T>(context: DvelopContext, options: DvelopOptions<T>): Promise<T>;
export async function getAuthSession<T>(
  context: DvelopContext,
  options: DvelopOptions<T | AuthSession> = {
    onResponse: onResponse
  }
): Promise<T | AuthSession> {
  return dvelopFetch(context, "/identityprovider/login", { method: "GET" }, options);
}
