import { DvelopContext } from "../../../../core/lib";
import { HttpConfig, HttpResponse, _defaultHttpRequestFunction } from "../../utils/http";

export interface GetImpersonatedAuthSessionIdParams {
  userId: string;
}

/**
 * Default transform-function provided to the {@link getImpersontedAuthSessionId}-function.
 * @internal
 * @category Authentication
 */
export function _getImpersonatedAuthSessionIdDefaultTransformFunction(response: HttpResponse, _: DvelopContext, __: GetImpersonatedAuthSessionIdParams): string {
  return response.data.authSessionId;
}

/**
 * Factory for the {@link getImpersonatedAuthSessionId}}-function. See internals for more information.
 * @typeparam T Return type of the {@link getImpersonatedAuthSessionId}-function. A corresponding transformFuntion has to be supplied.
 * @internal
 * @category Authentication
 */
export function _getImpersonatedAuthSessionIdFactory<T>(
  httpRequestFunction: (context: DvelopContext, config: HttpConfig) => Promise<HttpResponse>,
  transformFunction: (response: HttpResponse, context: DvelopContext, params: GetImpersonatedAuthSessionIdParams) => T,
): (context: DvelopContext, params: GetImpersonatedAuthSessionIdParams) => Promise<T> {
  return async (context: DvelopContext, params: GetImpersonatedAuthSessionIdParams) => {
    const response: HttpResponse = await httpRequestFunction(context, {
      method: "GET",
      url: "/identityprovider/impersonatesession",
      params: {
        userId: params.userId
      }
    });
    return transformFunction(response, context, params);
  };
}

/**
 * Returns an [AuthSession]{@link AuthSession} based on an API-Key. API-Keys can be generated by d.velop cloud tenant administrators.
 * **The AuthSessionId should be kept secret and never be publicly available.**
 *
 * @category Authentication
 *
 * @example ```typescript
 * //TODO
 * ```
 *
 */
/* istanbul ignore next */
export async function getImpersonatedAuthSessionId(context: DvelopContext, params: GetImpersonatedAuthSessionIdParams): Promise<string> {
  return _getImpersonatedAuthSessionIdFactory(_defaultHttpRequestFunction, _getImpersonatedAuthSessionIdDefaultTransformFunction)(context, params);
}